# config.yaml

# ------------------------
# General Configuration
# ------------------------
project_name: "object_detection_coco"
# output_dir: "outputs"
device: "cuda"  # or "cpu"

# ------------------------
# Dataset
# ------------------------
dataset:
  name: "COCO"
  root: "coco2017"
  train_folder: "train2017"
  val_folder: "val2017"
  test_folder: "test2017"
  annotation_train: "annotations/instances_train2017.json"
  annotation_val: "annotations/instances_val2017.json"
  num_classes: 91  # 80 COCO classes + 1 background

# ------------------------
# Model
# ------------------------
model:
  backbone: "resnet50"
  use_fpn: true
  pretrained: true
  freeze_backbone: false
  image_size: 600
   

# ------------------------
# Training
# ------------------------
training:
  epochs: 10
  batch_size: 6
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005
  lr_step_size: 3
  lr_gamma: 0.1
  seed: 42
  print_freq: 50
  num_workers: 4
  resume_checkpoint: "models/ckpt_step_67000.pth"

# ------------------------
# Evaluation
# ------------------------
evaluation:
  save_best_only: true
  metric: "mAP"  # mean Average Precision

output_dir: "./models"      
checkpoint_dir: "./checkpoints"  

